version: '3.8'

services:
  app:
    container_name: scraperDocker
    build:
      context: .
      dockerfile: ./src/Dockerfile
    depends_on:
      - db

  db:
    restart: always
    container_name: dbDocker
    ports:
      - "13306:3306"
    env_file:
      - ./src/.env
    build:
      context: .
      dockerfile: ./sqlDocker/Dockerfile
