version: '3.8'

services:
  app:
    container_name: scraperDocker
    build:
      context: .
      dockerfile: ./src/Dockerfile
    depends_on:
      - db

  db:
    restart: always
    container_name: dbDocker
    ports:
      - "13306:3306"
    env_file:
      - ./src/.env
    build:
      context: .
      dockerfile: ./sqlDocker/Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro

volumes:
  dbdata:
