version: '3.8'

services:
  app:
    container_name: scraperDocker
    network_mode: "host"
    # restart: always
    ports:
      - "19090:9090"
    build:
      context: .
      dockerfile: ./src/Dockerfile
    env_file:
      - ./src/standard_database_information.env
    depends_on:
      - db

  db:
    container_name: dbDocker
    restart: always
    ports:
      - "13306:3306"
    env_file:
      - ./src/standard_database_information.env
    build:
      context: .
      dockerfile: ./sqlDocker/Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
